package pipeline

import (
	"context"
	"fmt"
	"strings"

	"github.com/lrgalego/pictura/internal/store"
)

// Comics letter sounds as words: POOF!, STOMP!, Yaaawn…, Grr. Read aloud
// literally they come out as strange words ("Yaaawn" is heard as "Yon!").
// A sound-design pass decides, per line, which words are:
//
//   - speech: said by the speaker (or the narrator, for captions);
//   - vocal:  a sound the speaker makes — a yawn, a laugh, a growl — acted
//     in their own voice through an eleven_v3 audio tag;
//   - effect: a sound of the world — stomps, an explosion, wind, a punch —
//     generated by the sound-effects model from a short description.

// ReadingVersion is what a page's reading must be at to be read aloud:
// 2 = lettering read and sound design done. Pages read before sound design
// existed (1) are re-planned without being re-read.
const ReadingVersion = 2

// VocalTags are the eleven_v3 audio tags a character can perform. Each was
// checked against the real model: it is acted, not read aloud, even on its
// own ("[gulps]" came back silent and is not offered).
var VocalTags = []string{"yawns", "laughs", "giggles", "sighs", "gasps", "growls", "snores", "screams", "cries"}

// vocalSounds describes each vocal for the sound-effects model, the
// fallback when the voice returns nothing for a line that is only a tag.
var vocalSounds = map[string]string{
	"yawns":   "a big sleepy human yawn",
	"laughs":  "a short hearty human laugh",
	"giggles": "a light playful giggle",
	"sighs":   "a long tired human sigh",
	"gasps":   "a short surprised gasp",
	"growls":  "a low grumpy growl",
	"snores":  "soft, slow human snoring",
	"screams": "a short cartoon scream",
	"cries":   "a few seconds of sobbing",
}

// VocalSound is how a vocal is described to the sound-effects model.
func VocalSound(tag string) string {
	if s, ok := vocalSounds[tag]; ok {
		return s
	}
	return "a short human vocal sound: " + tag
}

// OnlyVocal reports whether every word of a line is performed as a vocal,
// and which one comes first.
func OnlyVocal(words []LetterWord) (string, bool) {
	if len(words) == 0 {
		return "", false
	}
	for _, w := range words {
		if w.Tag == "" {
			return "", false
		}
	}
	return words[0].Tag, true
}

// VocalSeconds is how long a vocal-only line is made when it falls back to
// the sound-effects model: a moment per word, within the effect limits.
func VocalSeconds(words int) float64 {
	return clampF(0.8*float64(words), 1.0, MaxEffectSeconds)
}

// Effect durations are asked for explicitly: the model bills per second.
const (
	MinEffectSeconds     = 0.5
	MaxEffectSeconds     = 4.0
	defaultEffectSeconds = 1.5
)

// Sounder makes a sound effect from a description.
type Sounder interface {
	Sound(ctx context.Context, prompt string, seconds float64) (*Speech, error)
}

// PlanLine is one read line as the sound designer sees it.
type PlanLine struct {
	Kind    string
	Speaker string // "" is the narrator
	Words   []string
}

// Part is a run of a line's words, From..To inclusive, and how it sounds.
type Part struct {
	From    int     `json:"from"`
	To      int     `json:"to"`
	Kind    string  `json:"kind"`    // speech, vocal, effect
	Tag     string  `json:"tag"`     // vocal: one of VocalTags
	Sound   string  `json:"sound"`   // effect: what it sounds like
	Seconds float64 `json:"seconds"` // effect: how long
}

var tagEnum = func() []any {
	out := []any{""}
	for _, t := range VocalTags {
		out = append(out, t)
	}
	return out
}()

var soundsSchema = obj(map[string]any{
	"lines": arr(obj(map[string]any{
		"line": integer("The line number as given"),
		"parts": arr(obj(map[string]any{
			"from":    integer("First word index of this part (0-based, inclusive)"),
			"to":      integer("Last word index of this part (inclusive)"),
			"kind":    map[string]any{"type": "string", "enum": []any{"speech", "vocal", "effect"}},
			"tag":     map[string]any{"type": "string", "enum": tagEnum, "description": "For vocal parts: the sound the speaker makes; empty otherwise"},
			"sound":   str("For effect parts: a short, concrete description of the sound for a sound designer (what makes it, material, size, mood), e.g. 'two heavy cartoon stomps on soft grass'; empty otherwise"),
			"seconds": map[string]any{"type": "number", "description": "For effect parts: length in seconds, 0.5 to 4; 0 otherwise"},
		}, "from", "to", "kind", "tag", "sound", "seconds")),
	}, "line", "parts")),
}, "lines")

const soundPersona = `You are the sound designer of an illustrated story that is read aloud to children, balloon by balloon. For every line of lettering you decide which words are spoken, which are a sound the speaker makes with their own voice, and which are sound effects of the world. Answer only with JSON matching the schema.`

// SoundPrompt is what the sound designer is asked about a page.
func SoundPrompt(story *store.Story, page *store.Page, lines []PlanLine) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Story: %s. World: %s\nPage %d: %s\n\n", story.Title, story.World, page.Number, page.Summary)
	b.WriteString(`Split every line below into parts that cover all its words, in order, without gaps or overlaps:
- "speech": words the speaker actually says (for captions and titles, the narrator reads them). Most words are speech.
- "vocal": an onomatopoeia for a sound the speaker makes with their own voice — a yawn ("Yaaawn"), a laugh ("Ha ha!", "Hee hee"), a giggle, a sigh ("Sigh…", "Haaah"), a gasp ("Eep!", "Gasp!"), a growl ("Grr"), snoring ("Zzz"), a scream ("Aaah!"), crying ("Waaah"). Give the tag that fits best.
- "effect": the sound of something in the world rather than a voice — impacts, footsteps, explosions, magic, weather, animals, machines ("STOMP!", "POOF!", "BOOM!", "Splash", "Tweet tweet", "Whoosh"). Describe it concretely for a sound designer and give its length, usually 0.5 to 2 seconds.
Words a character deliberately says are speech even when they are loud or short ("Stop!", "Help!"). Look at the page to judge what is happening. Keep a line as one speech part unless some words really are a sound.

LINES (word indices in brackets):
`)
	for i, l := range lines {
		who := l.Speaker
		if who == "" {
			who = "narrator"
		}
		fmt.Fprintf(&b, "Line %d (%s, %s):", i+1, l.Kind, who)
		for j, w := range l.Words {
			fmt.Fprintf(&b, " [%d]%s", j, w)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// PlanSounds runs the sound-design pass over a page's lines. A line whose
// plan does not fit its words is left as plain speech, so a sloppy answer
// never loses words.
func PlanSounds(ctx context.Context, ai AI, story *store.Story, page *store.Page, png []byte, lines []PlanLine) ([][]Part, error) {
	out := make([][]Part, len(lines))
	for i, l := range lines {
		out[i] = speechOnly(len(l.Words))
	}
	if len(lines) == 0 {
		return out, nil
	}
	var answer struct {
		Lines []struct {
			Line  int    `json:"line"`
			Parts []Part `json:"parts"`
		} `json:"lines"`
	}
	var images []Image
	if len(png) > 0 {
		images = []Image{{Label: "The comic page", PNG: png}}
	}
	if err := ai.ChatJSON(ctx, soundPersona, SoundPrompt(story, page, lines), images, "sounds", soundsSchema, &answer); err != nil {
		return nil, err
	}
	for _, a := range answer.Lines {
		i := a.Line - 1
		if i < 0 || i >= len(lines) {
			continue
		}
		if parts, ok := validParts(a.Parts, len(lines[i].Words)); ok {
			out[i] = parts
		}
	}
	return out, nil
}

func speechOnly(n int) []Part {
	if n == 0 {
		return nil
	}
	return []Part{{From: 0, To: n - 1, Kind: "speech"}}
}

// validParts checks that parts tile 0..n-1 in order and are well formed,
// normalizes them (clamped effect lengths, merged neighbours of the same
// kind) and reports whether they can be used.
func validParts(parts []Part, n int) ([]Part, bool) {
	if n == 0 || len(parts) == 0 {
		return nil, false
	}
	next := 0
	var out []Part
	for _, p := range parts {
		if p.From != next || p.To < p.From || p.To >= n {
			return nil, false
		}
		next = p.To + 1
		switch p.Kind {
		case "speech":
			p.Tag, p.Sound, p.Seconds = "", "", 0
		case "vocal":
			if !isVocalTag(p.Tag) {
				return nil, false
			}
			p.Sound, p.Seconds = "", 0
		case "effect":
			p.Sound = strings.TrimSpace(p.Sound)
			if p.Sound == "" {
				return nil, false
			}
			p.Tag = ""
			if p.Seconds <= 0 {
				p.Seconds = defaultEffectSeconds
			}
			p.Seconds = clampF(p.Seconds, MinEffectSeconds, MaxEffectSeconds)
		default:
			return nil, false
		}
		// Neighbouring speech runs are one run; so are repeats of one vocal.
		if k := len(out) - 1; k >= 0 && out[k].Kind == p.Kind && p.Kind != "effect" && out[k].Tag == p.Tag {
			out[k].To = p.To
			continue
		}
		out = append(out, p)
	}
	return out, next == n
}

func isVocalTag(t string) bool {
	for _, v := range VocalTags {
		if v == t {
			return true
		}
	}
	return false
}

// Script is what the voice is asked to say for a line, and which lettered
// words each spoken token stands for. Words are one token each (comic
// all-caps turned to sentence case, so they are not shouted); a run of
// words performed as a vocal becomes one audio tag, "[yawns]". A line that
// is only tags gets a trailing ellipsis, which eleven_v3 needs to perform
// a tag on its own.
func Script(words []LetterWord) (string, [][]int) {
	return ScriptWith("", words)
}

// ScriptWith is Script with a delivery: how the whole line is said, as an
// audio tag in front ("[whispers] ..."). The tag stands for no word.
func ScriptWith(delivery string, words []LetterWord) (string, [][]int) {
	text, owners := script(words)
	if d := cleanDelivery(delivery); d != "" && text != "" {
		return "[" + d + "] " + text, append([][]int{{}}, owners...)
	}
	return text, owners
}

// cleanDelivery keeps a delivery to a short plain tag.
func cleanDelivery(d string) string {
	d = strings.ToLower(strings.TrimSpace(strings.Trim(d, "[] ")))
	d = strings.Map(func(r rune) rune {
		if r == '[' || r == ']' || r == '\n' {
			return -1
		}
		return r
	}, d)
	if len(d) > 40 {
		d = d[:40]
	}
	return d
}

func script(words []LetterWord) (string, [][]int) {
	speech := make([]LetterWord, 0, len(words))
	for _, w := range words {
		if w.Tag == "" {
			speech = append(speech, w)
		}
	}
	spoken := strings.Fields(SpokenText(speech))
	var toks []string
	var owners [][]int
	si := 0
	for i := 0; i < len(words); i++ {
		if t := words[i].Tag; t != "" {
			run := []int{i}
			for i+1 < len(words) && words[i+1].Tag == t {
				i++
				run = append(run, i)
			}
			toks = append(toks, "["+t+"]")
			owners = append(owners, run)
			continue
		}
		tok := words[i].Text
		if si < len(spoken) {
			tok = spoken[si]
		}
		si++
		toks = append(toks, tok)
		owners = append(owners, []int{i})
	}
	if len(speech) == 0 && len(toks) > 0 {
		toks[len(toks)-1] += "..."
	}
	return strings.Join(toks, " "), owners
}

// AlignTokens gives every lettered word the time its token is spoken: a
// word said on its own gets its own timing, the words of a vocal share the
// tag's. When the voice split the text differently, tokens are matched by
// their position along the line.
func AlignTokens(n int, owners [][]int, text string, spoken []WordTiming) [][2]float64 {
	out := make([][2]float64, n)
	if len(spoken) == 0 || len(owners) == 0 {
		return out
	}
	toks := strings.Fields(text)
	tokTimes := make([][2]float64, len(owners))
	if len(spoken) == len(owners) {
		for i, w := range spoken {
			tokTimes[i] = [2]float64{w.Start, w.End}
		}
	} else {
		lettered := make([]LetterWord, len(toks))
		for i, t := range toks {
			lettered[i] = LetterWord{Text: t}
		}
		tokTimes = AlignWords(len(owners), lettered, spoken)
	}
	for ti, ws := range owners {
		for _, w := range ws {
			if w < n {
				out[w] = tokTimes[ti]
			}
		}
	}
	return out
}

// ---------- one line, adjusted by the writer ----------

// LineAdjustment is a new plan for one line: its parts, and how the spoken
// parts are said.
type LineAdjustment struct {
	Parts    []Part `json:"parts"`
	Delivery string `json:"delivery"`
}

var adjustLineSchema = obj(map[string]any{
	"parts":    soundsSchema["properties"].(map[string]any)["lines"].(map[string]any)["items"].(map[string]any)["properties"].(map[string]any)["parts"],
	"delivery": str("How the spoken words are said, as one short eleven_v3 audio tag without brackets — e.g. whispers, excited, sleepily, shouting, sarcastic, sad — or empty for a natural read"),
}, "parts", "delivery")

// AdjustLine re-plans one line from the writer's direction. The current
// plan is given so an unrelated part is kept.
func AdjustLine(ctx context.Context, ai AI, story *store.Story, page *store.Page, line PlanLine, current []Part, delivery, direction string) (*LineAdjustment, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "Story: %s. World: %s\nPage %d: %s\n\n", story.Title, story.World, page.Number, page.Summary)
	who := line.Speaker
	if who == "" {
		who = "narrator"
	}
	fmt.Fprintf(&b, "THE LINE (%s, %s):", line.Kind, who)
	for j, w := range line.Words {
		fmt.Fprintf(&b, " [%d]%s", j, w)
	}
	b.WriteString("\n\nHOW IT IS PLAYED NOW:\n")
	for _, p := range current {
		switch p.Kind {
		case "effect":
			fmt.Fprintf(&b, "- words %d-%d: sound effect %q, %.1fs\n", p.From, p.To, p.Sound, p.Seconds)
		case "vocal":
			fmt.Fprintf(&b, "- words %d-%d: the speaker performs [%s]\n", p.From, p.To, p.Tag)
		default:
			fmt.Fprintf(&b, "- words %d-%d: spoken\n", p.From, p.To)
		}
	}
	if delivery != "" {
		fmt.Fprintf(&b, "Spoken words are said: %s\n", delivery)
	}
	fmt.Fprintf(&b, "\nTHE WRITER'S DIRECTION:\n%s\n\nReturn the line's new plan following the direction: parts covering every word in order (speech, vocal with a tag, or effect with a concrete sound description and a length of 0.5 to 4 seconds), and a delivery for the spoken words. Change only what the direction asks for.", direction)
	var out LineAdjustment
	if err := ai.ChatJSON(ctx, soundPersona, b.String(), nil, "line", adjustLineSchema, &out); err != nil {
		return nil, err
	}
	parts, ok := validParts(out.Parts, len(line.Words))
	if !ok {
		return nil, fmt.Errorf("the new plan for this line did not cover its words; try the direction again in other words")
	}
	out.Parts, out.Delivery = parts, cleanDelivery(out.Delivery)
	return &out, nil
}
